In [1]:
#set:元素不可以重複、2個set可以做集合運算

#定義變數時，再把他的資料結構寫一次，強化他的提示功能
set1:set = {1,1,1,3,5,8,7,5,9,6}
set1.add(13)
set1

{1, 3, 5, 6, 7, 8, 9, 13}

In [5]:
for value in set1:
    print(value)

1
3
5
6
7
8
9
13


In [4]:
import numpy as np
array1:np.ndarray = np.array(range(1,11))

#陣列運算
array1 + 10 * 8

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90])

In [10]:
#在網路上看到別人寫的要回頭查說明書，才會有細節知道自己要怎麼寫
#display只能在ipynb上面使用

display(np.arange(1.6,7,0.5))
display(np.linspace(5,10,5))


array([1.6, 2.1, 2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1, 6.6])

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [20]:
np.random.random()
np.random.randn(2,5,2)
np.random.randint(1,7,size=(4,3))

array([[1, 5, 6],
       [6, 4, 5],
       [6, 5, 1],
       [5, 4, 6]])